[package]
name = "mugraph-simulator"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
bonsai-bt = "0.6.3"
clap = { version = "4.5.16", features = ["env", "derive"] }
color-eyre = "0.6.3"
core_affinity = "0.8.1"
ctrlc = "3.4.5"
futures-util = "0.3.30"
mugraph-client = { path = "../client" }
mugraph-node = { path = "../node" }
num_cpus = "1.16.0"
rand = "0.8.5"
rand_chacha = { version = "0.3.1", features = ["simd"] }
reqwest = { version = "0.12.5", features = ["blocking"] }
tokio = { version = "1.39.2", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
