[package]
name = "mugraph-simulator"
version = "0.0.1"
edition = "2021"

[dependencies]
indexmap = { workspace = true }
blake3 = { workspace = true }
bytes = { version = "1", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { workspace = true }
color-eyre = { workspace = true }
core_affinity = { workspace = true }
crossbeam-channel = { version = "0.5", default-features = false, features = ["std"] }
ctrlc = { workspace = true }
itertools = { workspace = true }
metrics = { workspace = true }
metrics-exporter-tcp = { workspace = true }
metrics-util = { workspace = true }
mugraph-core = { workspace = true }
mugraph-node = { workspace = true }
num_cpus = { workspace = true }
onlyerror = { workspace = true }
prost = { version = "0.12", default-features = false }
prost-types = { version = "0.12", default-features = false }
rand = { workspace = true }
rand_chacha = { workspace = true }
ratatui = { version = "0.28.0", default-features = false, features = ["crossterm"] }
redb = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
catppuccin = { version = "2.4.0" }

[build-dependencies]
prost-build = "0.12"
home = "=0.5.5"
