[package]
name = "mugraph-simulator"
version = "0.0.1"
edition = "2021"

[dependencies]
async-trait = "0.1.81"
bonsai-bt = "0.6.3"
color-eyre = "0.6.3"
core_affinity = "0.8.1"
mugraph-client = { path = "../client" }
num_cpus = "1.16.0"
rand = "0.8.5"
tokio = { version = "1.39.2", features = ["full"] }
