[package]
name = "mugraph-simulator"
version = "0.0.1"
edition = "2021"

[dependencies]
indexmap = { workspace = true }
blake3 = { workspace = true }
bytes = { version = "1", default-features = false }
clap = { workspace = true }
color-eyre = { workspace = true }
core_affinity = { workspace = true }
ctrlc = { workspace = true }
itertools = { workspace = true }
metrics = { workspace = true }
metrics-util = { workspace = true }
mugraph-core = { workspace = true }
mugraph-node = { workspace = true }
num_cpus = { workspace = true }
onlyerror = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
redb = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tikv-jemallocator = "0.6.0"