[package]
name = "mugraph-simulator"
version = "0.0.1"
edition = "2021"

[dependencies]
blake3 = { workspace = true }
clap = { workspace = true }
color-eyre = { workspace = true }
core_affinity = { workspace = true }
ctrlc = { workspace = true }
itertools = { workspace = true }
metrics = { workspace = true }
metrics-exporter-tcp = { workspace = true }
metrics-observer = { workspace = true }
mugraph-core = { workspace = true }
mugraph-node = { workspace = true }
num_cpus = { workspace = true }
onlyerror = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
redb = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
