[workspace]
resolver = "2"
members = [
  "circuits",
  "circuits/guest",
  "core",
  "examples",
  "node"
]

[workspace.dependencies]
mugraph-core = { path = "core" }
mugraph-circuits = { path = "circuits" }

hex = { version = "0.4.3", default-features = false, features = ["serde"] }
risc0-build = { version = "1.0.3" }
risc0-zkvm = { version = "1.0.3" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0.120"
onlyerror = { version = "0.1.4", default-features = false }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
