[workspace]
resolver = "2"
members = [
  "circuits",
  "circuits/swap",
  "circuits/swap/guest",
  "core",
  "node",
]

[workspace.dependencies]
mugraph-core = { path = "core" }
mugraph-circuits = { path = "circuits" }

hex = { version = "0.4.3", default-features = false, features = ["serde"] }
miette = { version = "7.2.0", features = ["fancy"] }
risc0-build = { version = "1.0.3" }
risc0-zkvm = { version = "1.0.3", features = ["std"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0.120"
thiserror = "1.0.63"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
