[workspace]
resolver = "2"
members = [
  "circuits",
  "circuits/guest",
  "core",
  "crypto",
  "examples",
  "node"
]

[workspace.dependencies]
mugraph-core = { path = "core" }

hex = { version = "0.4.3", default-features = false, features = ["serde"] }
onlyerror = { version = "0.1.4", default-features = false }
risc0-zkvm = { version = "1.0.3", default-features = false, features = ["std"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = { version = "0.10.8", default-features = false }

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true
