[workspace]
resolver = "2"
members = [
  "circuits",
  "circuits/guest",
  "core",
  "crypto",
  "examples",
  "node"
]

[workspace.dependencies]
mugraph-core = { path = "core" }

hex = { version = "0.4.3", default-features = false, features = ["serde"] }
onlyerror = { version = "0.1.4", default-features = false }
risc0-zkvm = { version = "1.0.3", default-features = false, features = ["std"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = { version = "0.10.8", default-features = false }
curve25519-dalek = { version = "4.1.2", default-features = false, features = ["rand_core"] }

[profile.dev]
opt-level = 3

[profile.release]
debug = 1
lto = true

[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
curve25519-dalek = { git = "https://github.com/risc0/curve25519-dalek", tag = "curve25519-4.1.2-risczero.0" }
