[package]
name = "mugraph-core"
version = "0.0.1"
edition = "2021"

[dependencies]
hex = { workspace = true }
serde = { workspace = true }
onlyerror = { workspace = true }
risc0-zkvm = { workspace = true, optional = true }
sha2 = { workspace = true }

[features]
default = []
guest = ["dep:risc0-zkvm"]
