[package]
name = "mugraph-core"
version = "0.0.1"
edition = "2021"

[dependencies]
blake2 = "0.10.6"
bulletproofs = "5.0.0"
curve25519-dalek = { version = "4.1.3", features = ["rand_core"] }
lazy_static = "1.5.0"
merlin = "3.0.0"
rand = "0.8.5"
rand_core = "0.6.4"
serde = { version = "1.0.204", features = ["derive"] }

[dev-dependencies]
proptest = "1.5.0"
test-strategy = "0.4.0"
