[package]
name = "mugraph-core"
version = "0.0.1"
edition = "2021"

[dependencies]
eyre = "0.6.12"
minicbor = { version = "0.24.2", features = ["std", "derive"] }
risc0-zkvm = { version = "1.0.5", features = ["std"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_bytes = "0.11.15"

proptest = { version = "1.5.0", optional = true }
test-strategy = { version = "0.4.0", optional = true }
bytemuck = "1.16.3"

[features]
default = ["proptest"]
proptest = [
  "dep:proptest",
  "dep:test-strategy"
]
