[package]
name = "mugraph-core"
version = "0.0.1"
edition = "2021"

[dependencies]
blake2 = "0.10.6"
curve25519-dalek = { version = "4.1.3", features = ["rand_core"] }
rand = "0.8.5"

[dev-dependencies]
proptest = "1.5.0"
test-strategy = "0.4.0"
