[package]
name = "mugraph-core"
version = "0.0.1"
edition = "2021"

[dependencies]
hex = { version = "0.4.3", default-features = false, features = ["serde"] }
onlyerror = { version = "0.1.4", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
sha2 = { version = "0.10.8", default-features = false }

[features]
default = []
std = [
  "hex/std",
  "serde/std",
  "onlyerror/std",
  "sha2/std"
]
