[package]
name = "mugraph-core"
version = "0.0.1"
edition = "2021"

[dependencies]
bytemuck = "1.16.3"
hex = { version = "0.4.3", default-features = false }

onlyerror = { version = "0.1.4", default-features = false }
risc0-zkvm = { version = "1.0.5", default-features = false, features = [
    "client",
] }
serde = { version = "1.0.204", default-features = false, features = ["derive"] }
serde_bytes = { version = "0.11.15" }

proptest = { version = "1.5.0", optional = true }
test-strategy = { version = "0.4.0", optional = true }
paste = "1.0.15"

[features]
default = []
std = ["hex/std", "serde/std", "serde_bytes/std"]
proptest = ["std", "dep:proptest", "dep:test-strategy"]
metal = ["risc0-zkvm/metal"]
cuda = ["risc0-zkvm/cuda"]
