[package]
name = "mugraph-core"
version = "0.0.1"
edition = "2021"

[dependencies]
onlyerror = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
sha2 = { workspace = true }
