[package]
name = "mugraph-core"
version = "0.0.1"
edition = "2021"

[dependencies]
hex = { workspace = true }
onlyerror = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
