[package]
name = "mugraph-examples"
version = "0.0.1"
edition = "2021"

[dependencies]
mugraph-programs = { path = "../programs" }
mugraph-core = { path = "../core" }
paste = "1.0.15"

rand = "0.8.5"
serde_json = "1.0.120"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
