[package]
name = "mugraph-examples"
version = "0.0.1"
edition = "2021"

[dependencies]
mugraph-circuits = { workspace = true }
mugraph-core = { workspace = true }
risc0-zkvm = { workspace = true }
serde_json = { workspace = true }
