[package]
name = "mugraph-examples"
version = "0.0.1"
edition = "2021"

[dependencies]
mugraph-circuits = { path = "../circuits" }
mugraph-core = { path = "../core" }
serde_json = "1.0.120"
tracing-subscriber = { version = "0.3.18", features = ["fmt"] }
