[package]
name = "mugraph-core-programs-guest"
version = "0.1.0"
edition = "2021"

[dependencies]
mugraph-core = { path = "../..", default-features = false }
risc0-zkvm = { version = "1.0.5", features = ["std"] }
