[package]
name = "mugraph-node"
version = "0.0.1"
edition = "2021"

[dependencies]
mugraph-circuits = { path = "../circuits" }
risc0-zkvm = { version = "1.0.3" }
serde = "1.0.204"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
