[package]
name = "mugraph-node"
version = "0.1.0"
edition = "2021"

[dependencies]
mugraph-core = { path = "../core" }
axum = "0.7.5"
redb = "2.1.1"
tempfile = "3.12.0"
color-eyre = "0.6.3"
rand = "0.8.5"
serde = { version = "1.0.208", features = ["derive"] }
tokio = { version = "1.39.2", features = ["full"] }
clap = { version = "4.5.16", features = ["env", "derive"] }
rand_chacha = { version = "0.3.1", features = ["simd"] }
serde_json = "1.0.125"
