[package]
name = "mugraph-node"
version = "0.0.1"
edition = "2021"

[dependencies]
mugraph-circuits = { path = "../circuits" }
risc0-zkvm = { version = "1.0.3" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
