[package]
name = "mugraph-core"
version = "0.0.1"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "1.0.5", features = ["std"] }
minicbor = { version = "0.24.2", default-features = false, features = ["derive"] }

[features]
default = []
std = [
  "minicbor/std"
]
