[package]
name = "mugraph-core"
version = "0.0.1"
edition = "2021"

[dependencies]
minicbor = { version = "0.24.2", default-features = false, features = ["derive"] }
risc0-zkvm = { version = "1.0.5", features = ["metal", "std"] }

[features]
default = []
std = [
  "minicbor/std"
]
