[package]
name = "mugraph-circuits"
version = "0.0.1"
edition = "2021"

[dependencies]
miette = { version = "7.2.0", features = ["fancy"] }
mugraph-circuits-swap = { path = "./swap" }
mugraph-core = { workspace = true }
risc0-zkvm = { workspace = true }
serde_json = "1.0.120"
thiserror = "1.0.63"
