[package]
name = "mugraph-circuits"
version = "0.0.1"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.0.3" }
serde = { version = "1.0", features = ["derive"] }

[package.metadata.risc0]
methods = ["guest"]
