[package]
name = "mugraph-circuits"
version = "0.0.1"
edition = "2021"

[build-dependencies]
risc0-build = { workspace = true }
serde = { workspace = true }

[package.metadata.risc0]
methods = ["guest"]
