[package]
name = "mugraph-crypto"
version = "0.0.1"
edition = "2021"

[dependencies]
mugraph-core = { workspace = true }

curve25519-dalek = { workspace = true }
rand_core = { version = "0.6.4" }
serde = { workspace = true }
sha2 = { workspace = true }
