[package]
name = "mugraph-crypto"
version = "0.0.1"
edition = "2021"

[dependencies]
mugraph-core = { workspace = true }

curve25519-dalek = { version = "4.1.3", features = ["rand_core"] }
rand_core = { version = "0.6.4" }
serde = { workspace = true }
